// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "mano1":return img`
........................
.......fff..............
....fffff2f.............
..ffeeeee22ff...........
.ffeeeeee222ff..........
.feeeefffeeeef..........
.fffffeee2222ef.........
fffe222fffffe2f.........
fffffffffeeefff.....cc..
fefe44ebbf44eef...ccdc..
.fee4d4bbfddef..ccddcc..
..feee4dddddfeecdddc....
...f2222222eeddcdcc.....
...f444445e44ddccc......
...ffffffffeeee.........
...fff...ff.............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "atack":return img`
........................
.......fff..............
....fffff2f.....1.......
..ffeeeee22ff...11......
.ffeeeeee222ff...11.....
.feeeefffeeeef....1.....
.fffffeee2222ef...11....
fffe222fffffe2f....1....
fffffffffeeefff....1....
fefe44ebbf44eef....1....
.fee4d4bbfddef.....1....
..feee4dddddf......1....
...f2222222e.......1....
...f444445e4e......1....
...fffffffedde.....1....
...fff...ffedccc..11....
............cddc..1.....
.............cddc.......
..............cddc......
...............c.c......
................cc......
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
